name: releasing the project
run-name: ${{ github.actor }} is releasing the project
on:
  push:
    tags:
      - v[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [ 18.x ]
    steps:
      - name: getting repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: downloading github CLI
        uses: wusatosi/setup-gh@v1
      - name: create an issue
        run: gh issue create --body "Автор релиза - ${{ github.triggering_actor }} \n Номер версии - ${{ github.action_ref}}" --title "New version!" --label "RELEASE" 
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}